ace/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="home"),
    url(r'^accounts/activate/complete/', views.registration_complete, name='reg_complete'),
    url(r'^accounts/update-profile/', views.update_profile, name='profile_update'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^terms-of-service/', views.terms_of_service, name='terms'),
    url(r'^about/', views.about_us, name='about_us'),
    url(r'^contact-us/', views.contact_us, name='contact'),
]

acerequests/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required
from .decorators import aircraft_permission_required, freight_permission_required


urlpatterns = [
	# Create #
    url(r'^create-aircraft-availability/$', login_required(views.AircraftCreateView.as_view()), name='create_aircraft'),
    url(r'^create-freight-availability/$', login_required(views.FreightCreateView.as_view()), name='create_freight'),
    # Edit #
    url(r'^edit-aircraft-availability/(?P<pk>\d+)/$', aircraft_permission_required(views.AircraftUpdateView.as_view()), name='update_aircraft'),
    url(r'^edit-freight-availability/(?P<pk>\d+)/$', freight_permission_required(views.FreightUpdateView.as_view()), name='update_freight'),
    # Delete #
    url(r'^delete-aircraft-availability/(?P<pk>\d+)/$', aircraft_permission_required(views.AircraftDeleteView.as_view()), name='delete_aircraft'),
    url(r'^delete-freight-availability/(?P<pk>\d+)/$', freight_permission_required(views.FreightDeleteView.as_view()), name='delete_freight'),
    # View Data #
    url(r'^my-profile/$', login_required(views.profile_list_view), name="profile_list_view"),
    # Dashboard #
    url(r'^dashboard-external/$', views.dashboard_view_external, name="dashboard_external"),
    url(r'^dashboard/$', login_required(views.dashboard_view_users), name="dashboard_users"),
    url(r'^aircraft-detail/(?P<pk>\d+)/$', login_required(views.aircraft_detail_view), name="aircraft_detail"),
    url(r'^freight-detail/(?P<pk>\d+)/$', login_required(views.freight_detail_view), name="freight_detail"),
]

ace/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from datetime import datetime
from phonenumber_field.modelfields import PhoneNumberField
from django_countries.fields import CountryField
from django.db.models.signals import post_save
from django.dispatch import receiver

class MyUserManager(BaseUserManager):

	    def _create_user(self, email, password, **extra_fields):
	    	if not email:
	    		raise ValueError('The Email must be set')
	    	email = self.normalize_email(email)
	    	user = self.model(email=email, **extra_fields)
	    	user.set_password(password)
	    	user.save()
	    	return user

	    def create_superuser(self, email, password, **extra_fields):
	    	extra_fields.setdefault('is_staff', True)
	    	extra_fields.setdefault('is_superuser', True)
	    	extra_fields.setdefault('is_active', True)

	    	if extra_fields.get('is_staff') is not True:
	    		raise ValueError('Superuser must have is_staff=True.')
	    	if extra_fields.get('is_superuser') is not True:
	    		raise ValueError('Superuser must have is_superuser=True.')

	    	return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(unique=True, null=True)
    date_joined = models.DateTimeField(default=datetime.now)

    is_staff = models.BooleanField(
    	_('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    USERNAME_FIELD = 'email'

    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email


class UserProfile(models.Model):
    
    CLIENT_CATEGORY = (
    ('Airline', 'Airline'),
    ('Broker', 'Broker / Freight Forwarder'),)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    category = models.CharField(choices=CLIENT_CATEGORY, max_length=26)
    company_name = models.CharField(max_length=500)
    contact_person = models.CharField(max_length=255)
    phone_number = PhoneNumberField()
    country = CountryField()
    city = models.CharField(max_length=500)

    def __str__(self):
        return self.company_name

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()

acerequests/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone


class AircraftAvailability(models.Model):
    REQ_AIRCRAFT = (
    ('A300', 'Airbus A300'),
    ('A310', 'Airbus A310'),
    ('A320', 'Airbus A320'),
    ('A330', 'Airbus A330'),
    ('AN12', 'Antonov AN12'),
    ('AN26', 'Antonov AN26'),
    ('AN32', 'Antonov AN32'),
    ('AN124', 'Antonov AN124'),
    ('AN225', 'Antonov AN225'),
    ('B727', 'Boeing 727'),
    ('B737', 'Boeing 737'),
    ('B747', 'Boeing 747'),
    ('B747-8', 'Boeing 747-8'),
    ('B757', 'Boeing 757'),
    ('B767', 'Boeing 767'),
    ('B777', 'Boeing 777'),
    ('Dash8', 'Bombardier Dash-8'),
    ('BAE146QT', 'British Aerospace 146QT'),
    ('BAEATPF', 'British Aerospace ATPF'),
    ('DC3', 'Douglas DC-3'),
    ('DC8', 'Douglas DC-8'),
    ('DC9', 'Douglas DC-9'),
    ('IL76', 'Ilyushin IL76'),
    ('IL96', 'Ilyushin IL96'),
    ('L100', 'Lockheed L100'),
    ('DC10', 'McDonnell Douglas DC10'),
    ('DC11', 'McDonnell Douglas DC11'),
    ('TU204', 'Tupolev TU204'),
    ('C208', 'Cessna Caravan'),
    ('LET410', 'LET 410'),
    ('SD330', 'Short 300'),
    ('ATR42', 'ATR 42'),
    ('ATR72', 'ATR 72'),
    ('Other', 'Other'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    from_airport = models.CharField(max_length=50, blank=False)
    to_airport = models.CharField(max_length=50, blank=False)
    aircraft_type = models.CharField(choices=REQ_AIRCRAFT, max_length=26, blank=False)
    max_payload = models.IntegerField(validators=[MaxValueValidator(200000), MinValueValidator(1)], null=True)
    max_volume = models.CharField(max_length=50, blank=True)
    date_required = models.DateField(blank=False)
    date_posted = models.DateTimeField(default=timezone.now)
    door_size = models.CharField(max_length=22, blank=True)
    max_pallets = models.CharField(max_length=22, blank=True)
    comments = models.TextField(max_length=250, blank=True)

    def __str__(self):
        return self.aircraft_type

    def get_absolute_url(self):
        return reverse('profile_list_view')

    class Meta:
        verbose_name_plural = "Aircraft Availabilities"


class FreightAvailability(models.Model):
    REQ_AIRCRAFT = (
    ('no_pref', 'No Preference'),
    ('A300', 'Airbus A300'),
    ('A310', 'Airbus A310'),
    ('A320', 'Airbus A320'),
    ('A330', 'Airbus A330'),
    ('AN12', 'Antonov AN12'),
    ('AN26', 'Antonov AN26'),
    ('AN32', 'Antonov AN32'),
    ('AN124', 'Antonov AN124'),
    ('AN225', 'Antonov AN225'),
    ('B727', 'Boeing 727'),
    ('B737', 'Boeing 737'),
    ('B747', 'Boeing 747'),
    ('B747-8', 'Boeing 747-8'),
    ('B757', 'Boeing 757'),
    ('B767', 'Boeing 767'),
    ('B777', 'Boeing 777'),
    ('Dash8', 'Bombardier Dash-8'),
    ('BAE146QT', 'British Aerospace 146QT'),
    ('BAEATPF', 'British Aerospace ATPF'),
    ('DC3', 'Douglas DC-3'),
    ('DC8', 'Douglas DC-8'),
    ('DC9', 'Douglas DC-9'),
    ('IL76', 'Ilyushin IL76'),
    ('IL96', 'Ilyushin IL96'),
    ('L100', 'Lockheed L100'),
    ('DC10', 'McDonnell Douglas DC10'),
    ('DC11', 'McDonnell Douglas DC11'),
    ('TU204', 'Tupolev TU204'),
    ('C208', 'Cessna Caravan'),
    ('LET410', 'LET 410'),
    ('SD330', 'Short 300'),
    ('ATR42', 'ATR 42'),
    ('ATR72', 'ATR 72'),
    ('Other', 'Other'),
    )
    CARGO_TYPE = (
    ('auto_parts', 'Automotive & Aeronautical Spare Parts'),
    ('election_materials', 'Election Materials'),
    ('general', 'General Cargo'),
    ('hazardous', 'Hazardous Materials'),
    ('humanitarian', 'Humanitarian & Relief Cargo'),
    ('live_stock', 'Live Stock'),
    ('luxury', 'Luxury Goods'),
    ('military', 'Military Support Equipment'),
    ('musical_band', 'Musical Band Tours'),
    ('oil_gas', 'Oil & Gas Industry Equipment'),
    ('perishable', 'Perishable Goods'),
    ('security_sensitive', 'Security Sensitive Monetary Cargo'),
    ('telecom_equipment', 'Telecommunications Equipment'),
    ('other', 'Other'),
    )
    CARGO_NATURE = (
    ('normal', 'Normal'),
    ('over_weight', 'Over Weight'),
    ('time_sensitive', 'Time Sensitive'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    from_airport = models.CharField(max_length=50, blank=False)
    to_airport = models.CharField(max_length=50, blank=False)
    aircraft_type = models.CharField(choices=REQ_AIRCRAFT, max_length=26, blank=False)
    max_payload = models.IntegerField(validators=[MaxValueValidator(200000), MinValueValidator(1)], null=True)
    max_volume = models.CharField(max_length=50, blank=True)
    date_required = models.DateField(blank=False)
    date_posted = models.DateTimeField(default=timezone.now)
    cargo_type = models.CharField(choices=CARGO_TYPE, max_length=26, blank=False)
    cargo_nature = models.CharField(choices=CARGO_NATURE, max_length=26, blank=True)
    number_pallets = models.IntegerField(validators=[MaxValueValidator(200), MinValueValidator(1)], null=True)
    comments = models.TextField(max_length=250, blank=True)

    def __str__(self):
        return self.aircraft_type

    def get_absolute_url(self):
        return reverse('profile_list_view')

    class Meta:
        verbose_name_plural = "Freight Availabilities"

ace/forms.py
from django import forms
from .models import UserProfile
from django_countries import countries


class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('category', 'company_name', 'contact_person', 'phone_number', 'country', 'city',)
        widgets = {
            'phone_number': forms.TextInput(attrs={'placeholder': 'including international code e.g. +1 647 123 0000'})
        }


class ContactUsForm(forms.Form):
    name = forms.CharField(required=True)
    company_name = forms.CharField(required=False)
    email = forms.EmailField(required=True)
    phone = forms.CharField(required=False)
    country = forms.ChoiceField(countries)
    message = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

acerequests/forms.py
from django import forms
from django_countries import countries


class ContactForm(forms.Form):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    phone = forms.CharField(required=False)
    company_name = forms.CharField(required=True)
    country = forms.ChoiceField(countries)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

ace/views.py
from django.shortcuts import render, redirect
from .forms import ProfileForm, ContactUsForm
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from registration.backends.default.views import RegistrationView
from django.template import Context
from django.template.loader import get_template
from django.views.generic import TemplateView


class IndexView(RegistrationView, TemplateView):
    template_name = "ace/index.html"


@login_required
@transaction.atomic
def registration_complete(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, instance=request.user.userprofile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, _('Your profile was successfully updated!'))
            return redirect('dashboard_users')
        else:
            messages.error(request, _('Please correct the error'))
    else:
        profile_form = ProfileForm(instance=request.user.userprofile)

    return render(request, 'registration/activation_complete.html', {'profile_form': profile_form})


@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, instance=request.user.userprofile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, _('Your profile was successfully updated!'))
            return redirect('profile_list_view')
        else:
            messages.error(request, _('Please correct the error'))
    else:
        profile_form = ProfileForm(instance=request.user.userprofile)

    return render(request, 'registration/update_profile.html', {'profile_form': profile_form})

def terms_of_service(request):

    return render(request, 'ace/terms_of_service.html')


def about_us(request):
    
    return render(request, 'ace/about.html')


def contact_us(request):
    form_class = ContactUsForm
    if request.method == 'POST':
        form = form_class(data=request.POST)
        if form.is_valid():
            name = request.POST.get(
                'name', '')
            company_name = request.POST.get(
                'company_name', '')
            email = request.POST.get(
                'email', '')
            phone = request.POST.get(
                'phone', '')
            country = request.POST.get(
                'country', '')
            message = request.POST.get(
                'message', '')

            template = get_template('acerequests/contact_template.txt')
            context = Context({
                'name': name,
                'email': email,
                'phone': phone,
                'company_name': company_name,
                'country': country,
                'message': message,
            })
            content = template.render(context)

            email = EmailMessage(
                "New contact form submission",
                content,
                "Air Cargo Exchange" + '',
                ['aircargoexchange@gmail.com'],
                headers={'Reply-To': email}
            )
            email.send()
            messages.success(request, 'Your message has been sent successfully, thank you!')
            return redirect('contact')  
    return render(request, 'ace/contact_us.html', {'form': form_class})

ace/templates/acerequests/aircraftavailability_form.html
{% extends "ace/base.html" %} {% load i18n %} {% load crispy_forms_tags %} 

{% block title %} Aircraft - {{ block.super }} 
{% endblock title %} 

{% block header %}
        <script>
         $(function() {
            var data = JSON.parse('{{ jsonData|safe }}');
            autoComplete = [];
                for (var i = 0, len = data.length; i < len; i++) {
                    autoComplete.push(data[i].iata + ", " + data[i].name);
                }
                $( "#id_from_airport" ).autocomplete({
                    source: autoComplete,
                    minLength: 3
                });
                $( "#id_to_airport" ).autocomplete({
                    source: autoComplete,
                    minLength: 3
                });
         });
        </script>

{{ block.super }}
{% endblock header %}

{% block content %}

<body>
    <h4>Create a new Aircraft Availability Request</h4>
    <h4>Empty Leg / Charter Flight / Schedule Flight</h4>
    <form method="post" class="form-style-9">
        {% csrf_token %} {{ form|crispy }}
        <input type="submit" value="Post to the community" class="btn btn-warning" />
    </form>

</body>

{% endblock content %}

ace/templates/acerequests/dashboard_external.html
{% extends "ace/base.html" %} {% load i18n %}

<html>

<body>

    {% block title %} Dashboard - {{ block.super }} {% endblock title %} 
    
    {% block content %}

    <h1 class="ext-dash-headline">Latest Requests</h1>
    <h3><a href="{% url 'registration_register' %}">Sign Up to Learn More !</a></h3>

    <div class="table-responsive">
        <table class="table table-hover" style="width: 60%">
            <tr>
                <td colspan="7" class="profile-table-head-ac">Aircraft Availability</td>
            </tr>
            <tr>
                <th>Origin</th>
                <th>Destination</th>
                <th>Aircraft Type</th>
                <th>Flight Date</th>
                <th>Max Payload</th>
                <th>Max Pallets</th>
            </tr>
            {% for requests in aircraft_requests %}
            <tr>
                <td>{{ requests.from_airport }}</td>
                <td>{{ requests.to_airport }}</td>
                <td>{{ requests.get_aircraft_type_display }}</td>
                <td>{{ requests.date_required }}</td>
                <td>{{ requests.max_payload }}</td>
                <td>{{ requests.max_pallets }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <div class="table-responsive">
        <table class="table table-hover" style="width: 60%">
            <tr>
                <td colspan="11" class="profile-table-head-frt">Freight Availability</td>
            </tr>
            <tr>
                <th>Origin</th>
                <th>Destination</th>
                <th>Date Required</th>
                <th>Max Payload</th>
                <th>Cargo Type</th>
                <th>Cargo Nature</th>

            </tr>
            {% for requests in freight_requests %}
            <tr>
                <td>{{ requests.from_airport }}</td>
                <td>{{ requests.to_airport }}</td>
                <td>{{ requests.date_required }}</td>
                <td>{{ requests.max_payload }}</td>
                <td>{{ requests.get_cargo_type_display }}</td>
                <td>{{ requests.get_cargo_nature_display }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% endblock content %}



</body>

</html>

ace/templates/acerequests/dashboard_freight_detail.html
{% extends "ace/base.html" %} {% load i18n %} {% load crispy_forms_tags %}

<html>
{% block title %} Dashboard - {{ block.super }} {% endblock title %} {% block content %}

<body>
    <div class="table-responsive">
        <table class="table table-hover" style="width: 70%;">
            <tr>
                <th>Cargo Type</th>
                <th>Cargo Nature</th>
                <th>Origin</th>
                <th>Destination</th>
                <th>Aircraft Type</th>
                <th>Date Required</th>
                <th>Max Payload</th>
                <th>Max Volume</th>
                <th>No. of Pallets</th>
                <th>Comments</th>
            </tr>
            <tr>
                <td>{{ freight_detail.get_cargo_type_display }}</td>
                <td>{{ freight_detail.get_cargo_nature_display }}</td>
                <td>{{ freight_detail.from_airport }}</td>
                <td>{{ freight_detail.to_airport }}</td>
                <td>{{ freight_detail.get_aircraft_type_display }}</td>
                <td>{{ freight_detail.date_required }}</td>
                <td>{{ freight_detail.max_payload }}</td>
                <td>{{ freight_detail.max_volume }}</td>
                <td>{{ freight_detail.number_pallets }}</td>
                <td>{{ freight_detail.comments }}</td>
            </tr>
        </table>
    </div>
    <h4>Contact Requester:</h4>
    <form method="post" class="form-contact">
    {{ form|crispy }}
        {% csrf_token %}
    <input type="submit" value="Submit" class="btn btn-warning" />
    </form>
    
    {% endblock content %}
</body>

</html>

ace/templates/acerequests/dashboard_users.html
{% extends "ace/base.html" %} {% load i18n %}

<html>

<body>

    {% block title %} Dashboard - {{ block.super }} {% endblock title %} 
    
    {% block content %}

    <h1 class="ext-dash-headline">Dashboard Latest Requests</h1>
    <div class="table-responsive">
        <table class="table table-hover" id="dash-table-ac" style="width: 60%">
            <tr>
                <td colspan="7" class="profile-table-head-ac">Aircraft Availability</td>
            </tr>
            <tr>
                <th>Origin</th>
                <th>Destination</th>
                <th>Aircraft Type</th>
                <th>Flight Date</th>
                <th>Max Payload</th>
                <th>Max Pallets</th>
            </tr>
            {% for requests in aircraft_requests %}
            <tr>
                <td>{{ requests.from_airport }}</td>
                <td>{{ requests.to_airport }}</td>
                <td>{{ requests.get_aircraft_type_display }}</td>
                <td>{{ requests.date_required }}</td>
                <td>{{ requests.max_payload }}</td>
                <td>{{ requests.max_pallets }}</td>
                <td><a href="{% url 'aircraft_detail' pk=requests.pk %}">Detail</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <div class="table-responsive">
        <table class="table table-hover" style="width: 60%">
            <tr>
                <td colspan="11" class="profile-table-head-frt">Freight Availability</td>
            </tr>
            <tr>
                <th>Origin</th>
                <th>Destination</th>
                <th>Date Required</th>
                <th>Max Payload</th>
                <th>Cargo Type</th>
                <th>Cargo Nature</th>

            </tr>
            {% for requests in freight_requests %}
            <tr>
                <td>{{ requests.from_airport }}</td>
                <td>{{ requests.to_airport }}</td>
                <td>{{ requests.date_required }}</td>
                <td>{{ requests.max_payload }}</td>
                <td>{{ requests.get_cargo_type_display }}</td>
                <td>{{ requests.get_cargo_nature_display }}</td>
                <td><a href="{% url 'freight_detail' pk=requests.pk %}">Detail</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% endblock content %}

</body>

</html>

ace/templates/acerequests/freightavailability_confirm_delete.html
{% extends "ace/base.html" %} {% load i18n %} 
{% block title %} Delete - {{ block.super }} {% endblock title %} 

{% block content %}

<h4>Are you sure, you want to delete the following:</h4>
<form method="post">
    {% csrf_token %}
    <div class="table-responsive">
        <table class="table table-hover" style="width: 70%;">
            <tr>
                <th>Origin</th>
                <th>Destination</th>
                <th>Aircraft Type</th>
                <th>Date Required</th>
                <th>Max Payload</th>
                <th>Max Volume</th>
                <th>Cargo Type</th>
                <th>Cargo Nature</th>
                <th>Pallets</th>
                <th>Comments</th>
            </tr>
            <tr>
                <td>{{ freightavailability.from_airport }}</td>
                <td>{{ freightavailability.to_airport }}</td>
                <td>{{ freightavailability.get_aircraft_type_display }}</td>
                <td>{{ freightavailability.date_required }}</td>
                <td>{{ freightavailability.max_payload }}</td>
                <td>{{ freightavailability.max_volume }}</td>
                <td>{{ freightavailability.get_cargo_type_display }}</td>
                <td>{{ freightavailability.get_cargo_nature_display }}</td>
                <td>{{ freightavailability.number_pallets }}</td>
                <td>{{ freightavailability.comments }}</td>
            </tr>
        </table>
    </div>
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'profile_list_view' %}" class="cancel-btn">Cancel</a>
</form>

{% endblock content %}

ace/templates/acerequests/profile_list_view.html
{% extends "ace/base.html" %}
{% load i18n %}

{% block title %}
    List View - {{ block.super }}
{% endblock title %}

{% block content %} 
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>

</head>

<body>

    <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li>
                    <a href="">My Requests</a>
                </li>
                <li>
                    <a href="#">Edit My Requests</a>
                </li>
                <li>
                    <a href="{% url 'profile_update' %}">Update My Profile</a>
                </li>
                <li>
                    <a href="{% url 'dashboard_users' %}">Dasboard</a>
                </li>
            </ul>
        </div>
        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">
              <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
            Toggle Menu
        </a>
        </div>
    <h3>Requests Posted By You</h3>
    <div class="table-responsive">
    <table class="table table-hover" style="width: 70%;">
        <tr>
        <td colspan="9" class="profile-table-head-ac">Aircraft Availability Requests</td>
        </tr>
        <tr>
            <th>Origin</th>
            <th>Destination</th>
            <th>Aircraft Type</th>
            <th>Flight Date</th>
            <th>Max Payload</th>
            <th>Door Size</th>
            <th>Max Pallets</th>
            <th>Comments</th>
            <th>Edit/Delete</th>
        </tr>
    {% for requests in user_aircraft_requests %}
        <tr>
            <td>{{ requests.from_airport }}</td>
            <td>{{ requests.to_airport }}</td>
            <td>{{ requests.get_aircraft_type_display }}</td>
            <td>{{ requests.date_required }}</td>
            <td>{{ requests.max_payload }}</td>
            <td>{{ requests.door_size }}</td>
            <td>{{ requests.max_pallets }}</td>
            <td>{{ requests.comments }}</td>
            <td>
                <a href="{% url 'update_aircraft' pk=requests.pk %}">Edit |</a>
                <a href="{% url 'delete_aircraft' pk=requests.pk %}">Delete</a>
            </td>
        </tr>
    {% endfor %}    
    </table>
    </div>
    
    <div class="table-responsive">
    <table class="table table-hover" style="width: 70%;">
        <tr>
        <td colspan="11" class="profile-table-head-frt">Freight Availability Requests</td>
        </tr>
        <tr>
            <th>Origin</th>
            <th>Destination</th>
            <th>Aircraft Type</th>
            <th>Date Required</th>
            <th>Max Payload</th>
            <th>Max Volume</th>
            <th>Cargo Type</th>
            <th>Cargo Nature</th>
            <th>Pallets</th>
            <th>Comments</th>
            <th>Edit/Delete</th>
        </tr>
    {% for requests in user_freight_requests %}
        <tr>
            <td>{{ requests.from_airport }}</td>
            <td>{{ requests.to_airport }}</td>
            <td>{{ requests.get_aircraft_type_display }}</td>
            <td>{{ requests.date_required }}</td>
            <td>{{ requests.max_payload }}</td>
            <td>{{ requests.max_volume }}</td>
            <td>{{ requests.get_cargo_type_display }}</td>
            <td>{{ requests.get_cargo_nature_display }}</td>
            <td>{{ requests.number_pallets }}</td>
            <td>{{ requests.comments }}</td>
            <td><a href="{% url 'update_freight' pk=requests.pk %}">Edit |</a>
                <a href="{% url 'delete_freight' pk=requests.pk %}">Delete</a>
            </td>
        </tr>
    {% endfor %}    
    </table>
    </div>
    
    
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>
  
{% endblock content %}